version: '3.7'

services:
    mysimpleapi:
        build: ./simple-api-student-main/
        networks:
          - my-network
        depends_on:
          - mydatabase

    mydatabase:
        build: ./database/
        networks:
          - my-network

    myhttp:
        build: ./http-server/
        ports:
          - 8080:80
        networks:
          - my-network
        depends_on:
          - mysimpleapi

networks:
    my-network:
