FROM openjdk:17
#TODO: Choose a java JRE
# TODO:  Add the compiled java (aka bytecode, aka .class)
COPY Main.class  /tmp
WORKDIR /tmp
ENTRYPOINT [ "java", "Main" ]

# TODO: Run the Java with: “java Main” command.
